=== Emile-Muller/healthcheckr/app/schemas/service.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "ping_url": {
        "type": "string"
      },
      "attributions": {
        "type": "string"
      }
    },
    "required": [
      "description",
      "type",
      "url"
    ]
  }

=== Emile-Muller/healthcheckr/data/services/opm_mars_basemap.json
{
    "title":"OPM Mars Basemap v0.2",
    "description":"This basemap of Mars in a combination of multiple raster and vector datasets that provides a characteristic view of the planet for a broader audience.",
    "type":"XYZ",
    "url":"https://cartocdn-gusc.global.ssl.fastly.net/opmbuilder/api/v1/map/named/opm-mars-basemap-v0-2/all/{z}/{x}/{y}.png",
    "ping_url":"https://cartocdn-gusc.global.ssl.fastly.net/opmbuilder/api/v1/map/named/opm-mars-basemap-v0-2/all/3/1/1.png",
    "attributions":"OpenPlanetary"        
}
